import Head from "next/head";
import type { GetServerSideProps, NextPage } from "next";
import { Inter } from "next/font/google";
import { fetchCategories } from "@/http";
import { AxiosResponse } from "axios";
import { ICollectionResponse, ICategory } from "@/types";
const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-primary">Welcome to Coders Blog</h1>
      </main>
    </>
  );
};

{
  /* create the next.js server side rendering */
}
export const getServerSideProps: GetServerSideProps = async () => {
  // fetch the categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  console.log("categories :", categories);
  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};
export default Home;
